### ISSUE TITLE
Latest docker image is pointing to 2.19 instead of 3

### ISSUE THREAD

**Issue by jdfranel** [ekreative/php-cs-fixer-docker#6]
Hello.

I encountered an unexpected result when running the latest image.

According to the readme, the "latest" image is supposed to be the same as the version 3 but when checking the [image layer](https://hub.docker.com/layers/ekreative/php-cs-fixer/latest/images/sha256-b3574cf225bbdebfa15e918c156ba2ceb7b2058c9daa8a6202e05b9b27eff8f1?context=explore) the environment variable `PHP_CS_FIXER_VERISON` is set to `2.19.0`.

**Comment by mcfedr** [comment]
Switched to new Github builds and fixed this.
